In [2]:
import numpy as np
import pandas as pd
from os import getcwd
from os.path import join, dirname
import pickle

from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# Normalizing data
def normalizing
    scaler = StandardScaler()
    # transform data
    scaled = scaler.fit_transform(data)
    print(scaled)

In [3]:
# Prepare data
data_folder_path = join(dirname(getcwd()), 'data')
data = pd.read_pickle(join(data_folder_path, 'cleaned_df.pkl'))
data.head()

,Transaction,SystemF1,SystemF2,SystemF3,SystemF4,SystemF5,Account_Page,Account_Page_Time,Info_Page,Info_Page_Time,...,GoogleAnalytics_BR,GoogleAnalytics_ER,GoogleAnalytics_PV,Ad_Campaign_1,Ad_Campaign2,Ad_Campaign3,Wday_n,CusType_New,CusType_Other,CusType_Returning
0,0,1,2,7,10,2,0,0.000000,0,0.0,...,0.200000,0.200000,0.0,0,0,0,1,0.0,0.0,1.0
1,0,2,2,3,2,3,10,147.458333,4,216.5,...,0.000000,0.010046,0.0,0,0,0,1,0.0,0.0,1.0
2,0,2,2,1,2,1,0,0.000000,0,0.0,...,0.000000,0.033333,0.0,0,0,0,1,1.0,0.0,0.0
3,0,2,2,2,6,1,0,0.000000,0,0.0,...,0.011765,0.052941,0.0,0,0,0,1,0.0,0.0,1.0
4,0,2,2,4,10,3,0,0.000000,2,45.0,...,0.015385,0.046154,0.0,0,0,0,1,0.0,0.0,1.0

In [ ]:
train=data.sample(frac=0.8,random_state=200)
test=data.drop(train.index)

In [ ]:
#Normalize data